# Tobias Schnabel | 833002303
rm(list = ls())
library(stargazer)
library(xtable)
library(ggpubr)
library(boot)
library(caret)
library(class)
library(ISLR2)
library(MASS)
library(glmnet)
library(pls)
library(lmvar)
library(leaps)
library(gam)
library(gbm)
library(randomForest)
library(httpgd)
library(e1071)


#9.7(a)
library(ISLR)
var <- ifelse(Auto$mpg > median(Auto$mpg),1,0)
Auto$mpglevel<- as.factor(var)

